# Generated by Django 2.2.3 on 2020-05-18 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text1', models.TextField(blank=True, verbose_name='封面简介')),
                ('text2', models.TextField(blank=True, verbose_name='博客简介')),
                ('text3', models.TextField(blank=True, verbose_name='关于简介')),
                ('image1', models.ImageField(default='coverimage/zhixiang1.jpg', upload_to='coverimage/', verbose_name='封面图片')),
                ('image2', models.ImageField(default='coverimage/zhixiang2.jpg', upload_to='coverimage/', verbose_name='博客图片')),
                ('image3', models.ImageField(default='coverimage/zhixiang1.jpg', upload_to='coverimage/', verbose_name='关于图片')),
            ],
            options={
                'verbose_name': '个人简介',
                'verbose_name_plural': '个人简介',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('short_title', models.CharField(blank=True, max_length=50, verbose_name='简写标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(verbose_name='修改时间')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='摘要')),
                ('image', models.ImageField(default='coverimage/default.jpg', upload_to='coverimage/%Y/%m/%d/', verbose_name='封面图片')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created_time'],
            },
        ),
    ]
